let constants = {
	'GET_ARTICLES': 'GET_ARTICLES',
	'SET_CURRENT_ARTICLE': 'SET_CURRENT_ARTICLE',
	'SAVE_ARTICLE': 'SAVE_ARTICLE',
	'CREATE_ARTICLE': 'CREATE_ARTICLE',
	'EDIT_ARTICLE': 'EDIT_ARTICLE',
	'USER_LOGIN': 'USER_LOGIN',
	'USER_LOGOUT': 'USER_LOGOUT',
	'VIEW_ACTION': 'VIEW_ACTION',
	'SERVER_ACTION': 'SERVER_ACTION'
};

export default constants;
